name: nextcloud-influxdb-tracks-importer docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  buildAndPush:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: |
        make build

    - name: Push the Docker image
      run: |
        echo ${{ secrets.PAT_GHCR }} | docker login ghcr.io -u windsource --password-stdin
        make push
        
